[modules.dagger-dang-sdk]
source = "github.com/dagger/dang-sdk"

[modules.e2e]
source = ".dagger/modules/e2e"

[sdks.dang]
module = "dagger-dang-sdk"

[sdks.dang.scopes."pyproject"]
is-module = true
name = "pyproject"
