name = "e2e"
engineVersion = "v1.0.0-beta.14"

[runtime]
  source = "dang"

[[dependencies]]
  name = "mypy"
  source = "../../../mypy"

[[dependencies]]
  name = "pyproject"
  source = "../../../pyproject"

[[dependencies]]
  name = "pytest"
  source = "../../../pytest"

[[dependencies]]
  name = "ruff"
  source = "../../../ruff"

[[dependencies]]
  name = "ty"
  source = "../../../ty"

[[dependencies]]
  name = "uv"
  source = "../../../uv"
